### ISSUE TITLE
Copied code

### ISSUE THREAD

**Issue by mafredri** [Luxurioust/excelize#1]
Hey,

I just came across your project and noticed there is a lot of copied code from [`tealeg/xlsx`](https://github.com/tealeg/xlsx) without attribution. Especially [`xmlSharedStrings.go`](https://github.com/Luxurioust/excelize/blob/3c4ad28db75108dfd974b994df26ec7f33a69be7/xmlSharedStrings.go) which is a direct copy paste of `tealeg/xlsx` [`xmlSharedStrings.go`](https://github.com/tealeg/xlsx/blob/master/xmlSharedStrings.go), comments and all.

It's nice to see more xlsx action in the Golang world, but have you considered just contributing to `tealeg/xlsx` instead?

**Comment by Luxurioust** [comment]
Thanks for your issue, I'm sorry I didn't comments some code copy from `tealeg/xlsx`. I have update README file and add comments in all file for this issue. `tealeg/xlsx` provided much more function. I'm very glad to contribute code to it. Sometimes I need to save file without losing original charts of XLSX, so I had rewrite a simple library.

**Comment by mafredri** [comment]
Thanks for amending it so quickly 👍 !

I can also see a real benefit in being able to edit the original without modifying it. I've actually played with this idea myself, especially for really large xlsx files that do not fit in memory. In those cases it would be need to be disk-backed whilst still permitting editing.
