### ISSUE TITLE
Question: How to get all cells & rows?

### ISSUE THREAD

**Issue by jordyvandomselaar** [Luxurioust/excelize#16]
As the title says, how to get all rows and their cells? I don't know beforehand how many rows or cells there'll be.

**Comment by Luxurioust** [comment]
@jordyvandomselaar Thanks for your issue. You can use [func (*File) GetRows](https://godoc.org/github.com/Luxurioust/excelize#File.GetRows) to get all the rows in a sheet like this:

```golang
rows := xlsx.GetRows("Sheet1")
for _, row := range rows {
    for _, colCell := range row {
        fmt.Print(colCell, "\t")
    }
    fmt.Println()
}
```

The full API docs can be seen on [godoc.org](https://godoc.org/github.com/Luxurioust/excelize).

**Comment by jordyvandomselaar** [comment]
Hmm, kept returning an empty slice.

**Comment by Luxurioust** [comment]
Verify that the given sheet index is valid or attach your code and .xlsx file if possible.

**Comment by Luxurioust** [comment]
@jordyvandomselaar Verify that the given sheet index is valid or attach your code and .xlsx file if possible.

**Comment by jordyvandomselaar** [comment]
I ended up using another lib, but I ran the functions to get the active sheet name which I used in `getRows()`
