### ISSUE TITLE
Not Working "Reading XLSX file sample"

### ISSUE THREAD

**Issue by jof4002** [Luxurioust/excelize#17]
[Workbook.xlsx](https://github.com/Luxurioust/excelize/files/722660/Workbook.xlsx)
I attached my test file.

I made that file and run homepage's "Reading XLSX file sample" code
I expected :
test text
1       2 ...

But i got :

1       2 ...

But when I input some values to "A?" of "Sheet1" I got the expected result.

I think cell.go's line 26
	if rows <= xAxis {
		return ""
	}
return an empty string.

**Comment by Luxurioust** [comment]
@jof4002 Thans for your issue, I have fixed this bug.
