### ISSUE TITLE
Memory usage on large XLSXs goes way too high

### ISSUE THREAD

**Issue by pztrn** [Luxurioust/excelize#20]
As well as in https://github.com/tealeg/xlsx/issues/186, this library suffers from memory eating while trying to parse large files.

For example I have 7mb file (~60k rows with ~40 columns for each row) which parsed with tealeg/xlsx into 700mb of RAM, while this library eats almost whole gigabyte.

Any plans to provide an iterator which will be memory-friendly?

**Comment by Luxurioust** [comment]
Thanks for your issue. Yes, this library will be having performance problems on handling with large files, I also recorded this problem on the Wiki. Improving the performance will be part of the plan, but I can't guarantee an accurate time to submit code.

**Comment by Luxurioust** [comment]
@pztrn Hi Stanislav, I have done some optimization on this issue. I call Token to read tokens one by one instead Unmarshal. In my test, parsing 24MB file (40000 rows, 220 columns) occupies memory about 840MB now, the values of the cells are all strings.

**Comment by pztrn** [comment]
Hey and thanks!

I think it's still too high, especially if you'll parse large files. What about streamlined interface?
