### ISSUE TITLE
Merge with tealeg/xlsx ?

### ISSUE THREAD

**Issue by boxpear** [Luxurioust/excelize#24]
Feel free to delete if off-topic.

I see two reasonably popular XLSX go packages, this and tealeg/xlsx.  Is it worth trying to merge to one unified effort?

**Comment by Luxurioust** [comment]
Thanks for your issue, tealeg/xlsx provided much more function. It is object-oriented style, and the implementation of these two libraries is not the same. At first I created this lib in order to support the modification of Excel with charts. I'm glad to contribute code to tealeg/xlsx.
