### ISSUE TITLE
Setting Value Efficiency

### ISSUE THREAD

**Issue by coolboy0002001** [Luxurioust/excelize#26]
When setting value repeatedly with many cols, it runs very slow!
----------------------------------------
	col := "A"
	for i := 0; ; i++ {
		col += "A"
		xlsx.SetCellStr("Sheet1", col+"1", "a")
		fmt.Println("set value")
	}
-----------------------------------------

**Comment by Luxurioust** [comment]
@coolboy0002001 Thanks for your issue. I've done some optimization on this issue. The benchmark report of the current version of this library is shown on the [wiki page](https://github.com/Luxurioust/excelize/wiki). I will continue to focus on performance issues and optimize it. In addition, as a performance-related problem, I close this and merge it into the issue #29 is still discussing this problem.
