### ISSUE TITLE
Inserted Picture Print Supporting

### ISSUE THREAD

**Issue by coolboy0002001** [Luxurioust/excelize#27]
When printing file, inserted pictures are hidden.
I found a property setting.
![_20170227211942](https://cloud.githubusercontent.com/assets/8806281/23362839/9e969a22-fd32-11e6-99f5-3f4592aafb25.png)

**Comment by Luxurioust** [comment]
Thank you for your issue. I have add printing settings support for the library. Note that function `AddPicture()` parameters has been changed.
