### ISSUE TITLE
Adding Excel data validation to type xlsxWorksheet 

### ISSUE THREAD

**Issue by cehuff** [Luxurioust/excelize#28]
Added data validation types in attached xlsxWorksheet.go. 

[xmlWorkbook.zip](https://github.com/Luxurioust/excelize/files/814641/xmlWorkbook.zip)

With this change cell data validations are preserved when calling OpenFile("excel.xlsx") and then WriteTo("excel.xlsx").

Thanks!

**Comment by Luxurioust** [comment]
@cehuff Thanks for your issue. But sorry, I didn't understand what you meant. I can't find any differences in the attachments. Will not be lost exist data validation properties after saving by calling ```WriteTo()```. Do you mean if you want to add additional feature to support set data validation for a cell?

**Comment by Luxurioust** [comment]
@cehuff Thanks for your issue. I have fix it.

**Comment by cehuff** [comment]
Greetings Ri Xu,


Sorry, I attached the wrong source. Here is xlsxWorksheet.go.


Regards,

C. Huff


________________________________
