### ISSUE TITLE
Delete sheet from workbook

### ISSUE THREAD

**Issue by rpokupec** [Luxurioust/excelize#30]
Hi,

Is it possible to implement new function which can delete/remove particular sheet?

**Comment by Luxurioust** [comment]
@rpokupec Thanks for your issue. I think deleting a sheet from workbook will be affected references to charts or formulas in other sheet. To support this feature maybe needs to evaluated.

**Comment by rpokupec** [comment]
Sure, no problem. I just thought it would be a nice feature to have in case when you do some operations with the data and put the results in new sheet and in such cases some sheet(s) can become obsolete.

**Comment by Luxurioust** [comment]
@rpokupec I have added function `DeleteSheet()` to support sheet from a workbook.

**Comment by rpokupec** [comment]
Thanks.
