### ISSUE TITLE
Leading space(s) are missing

### ISSUE THREAD

**Issue by rpokupec** [Luxurioust/excelize#32]
Hi,

When I create workbook and do some entries to the cells I noticed that if there are some leading spaces in front of the text, they are missing.
In case if I open the workbook with excel and enter some text with leading spaces they are corretly entered to the cell.

**Comment by Luxurioust** [comment]
@rpokupec Thanks for your issue, I have fixed this issue.

**Comment by rpokupec** [comment]
Thanks.

**Comment by huyhoang1996** [comment]
OMG! It still now. It don't fix

**Comment by xuri** [comment]
Hi @huyhoang1996, thanks for your feedback. I have fixed it.
