### ISSUE TITLE
duplicate sheets

### ISSUE THREAD

**Issue by mhlo** [Luxurioust/excelize#33]
Capability to duplicate a sheet, like PowerShell/excel's $wb.sheets.item(1).copy($wb.sheets.item(2)). Perhaps something like:

// sheet at index 1 already exists...
xlsx.NewSheet(2, "sheet2")
xlsx.CopySheet(1, 2)

**Comment by muhrifqii** [comment]
@xuri in my case, copy sheet didn't work. I ran this using master branch on a526e9040491

```go
n := "1"
last := f.NewSheet(n)
err := f.CopySheet(1, last)
```

above code will return error about wrong index. The actual excel only contain 1 sheet, but the value `last` returns 3.

when I ran this

```go
n := "1"
last := f.NewSheet(n)
err := f.CopySheet(1, 2)
```
that will not return any error, but the sheets is not copied into newly created sheet. I will send the excel file via email if it have to.

**Comment by xuri** [comment]
Hi @muhrifqii, thanks for your feedback, you can send me the file with credential data masking. `xuri.me[at]gmail.com`

**Comment by xuri** [comment]
Hi @muhrifqii, I have fixed this issue. Please try to upgrade the library with the master branch code, and this bug fix will be published in the next release version. Also, we need to get the source worksheet index before copy to the target worksheet:

```go
package main

import "github.com/360EntSecGroup-Skylar/excelize"

func main() {
	n := "1"
	f, err := excelize.OpenFile("blank.xlsx")
	if err != nil {
		panic(err)
	}
	last := f.NewSheet(n)
	if err := f.CopySheet(f.GetSheetIndex("Sheet2"), last); err != nil {
		panic(err)
	}
	f.SetActiveSheet(last)
	if err := f.SaveAs("./Book1.xlsx"); err != nil {
		panic(err)
	}
}
```
