### ISSUE TITLE
How to get a picture in a cell ?

### ISSUE THREAD

**Issue by JermineHu** [Luxurioust/excelize#34]
I need  import some data to mongodb and the row data  have a picture need to save another path !  I don't want to upload excel and pictures two times, so how do I get a picture from the cell ? Here are my previous snippets and related links([https://github.com/tealeg/xlsx/issues/49](url)), but there's no real solution,that made me a little anxious !   Thanks a lot !  

![qq20170323-173945](https://cloud.githubusercontent.com/assets/18027793/24286501/775fc546-10b0-11e7-9c9d-eb379146d86e.png)

![qq20170323-174044](https://cloud.githubusercontent.com/assets/18027793/24286635/f3fa2ccc-10b0-11e7-9d2c-b5483f4895e4.png)

![qq20170324-175016](https://cloud.githubusercontent.com/assets/18027793/24289007/6c5da582-10ba-11e7-8208-e5e105d88707.png)

**Comment by Luxurioust** [comment]
@JermineHu Thanks for your issue. I'll consider adding the function `GetPicture()` to get the file handle.

**Comment by JermineHu** [comment]
@Luxurioust  Thanks a lot !

**Comment by Luxurioust** [comment]
@JermineHu Hi, I have added new function `GetPicture()` to use this please reference [godoc](https://godoc.org/github.com/Luxurioust/excelize).

**Comment by JermineHu** [comment]
Quickly response very commendable, You are a good person to help others! Persistent optimization is great ! Thanks  again !

**Comment by JermineHu** [comment]
@Luxurioust   Quickly response very commendable, You are a good person to help others! Persistent optimization is great ! Thanks  again !
