### ISSUE TITLE
Use builtin `map` instead of home-built

### ISSUE THREAD

**Issue by md2perpe** [Luxurioust/excelize#4]
As I understand it, the order of `FileList` elements in the slice is not of importance. Therefore, instead of a slice of the struct `FileList` (containing `Key` and `Value`), you could use a `map[string] string`.

https://gobyexample.com/maps
https://blog.golang.org/go-maps-in-action

**Comment by Luxurioust** [comment]
Thank you so much for your suggestion. I have to update package use ```map[string]string``` instead of ```[]FileList```. In addition, I intend to use the object-oriented approach reconstruction package.
