### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by refflex** [Luxurioust/excelize#42]
Hi. Example does not work. Library created bad xlsx file (in attach).
	xlsx := excelize.CreateFile()
	xlsx.NewSheet(2, "Sheet2")
	xlsx.SetCellValue("Sheet2", "A2", "Hello world.")
	xlsx.SetCellValue("Sheet1", "B2", 100)
	xlsx.SetActiveSheet(2)
	err = xlsx.WriteTo("Workbook.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
[Workbook.xlsx](https://github.com/Luxurioust/excelize/files/935674/Workbook.xlsx)

**Comment by tvc-dps** [comment]
It works for me, can you share full code?

**Comment by refflex** [comment]
It's full code. I copy/paste and build.

package main

import (
	"fmt"
	"os"

	"github.com/Luxurioust/excelize"
)

func main() {
	xlsx := excelize.CreateFile()
	xlsx.NewSheet(2, "Sheet2")
	xlsx.SetCellValue("Sheet2", "A2", "Hello world.")
	xlsx.SetCellValue("Sheet1", "B2", 100)
	xlsx.SetActiveSheet(2)
	err := xlsx.WriteTo("Workbook.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

**Comment by Luxurioust** [comment]
@refflex Check the Go version you are using. This library needs Go version 1.8 or later after fixed issue #32 for collecting XML all attributes. Relate issue #35 & #39.

**Comment by refflex** [comment]
Many thanks! My version Go was 1.7.5. I updated to the latest 1.8.1 and all worked.
