### ISSUE TITLE
How to set font to Bold, Italic, etc?

### ISSUE THREAD

**Issue by mewben** [Luxurioust/excelize#45]
I searched the docs and the code but didn't find anything to set the font style to bold, italic etc.

**Comment by Luxurioust** [comment]
@mewben Thanks for your issue. I have add font bold, italic and underline style support for function `SetCellStyle()` to use this please reference [godoc](https://godoc.org/github.com/Luxurioust/excelize).

**Comment by mewben** [comment]
Sweeeet! Thank you very much.

**Comment by luojiego** [comment]
nice! 
```
style, _ := file.NewStyle(`{"font":{"bold":false,"italic":false,"family":"JetBrains Mono","size":11,"color":"#000000"}}`)

file.SetCellValue("Sheet1", "A1", "A1", style)
```
I can set my favorite font!

**Comment by spyhunter925** [comment]
I tried the example in the documentation, as well as the comment above, but I got this error when I tried to run it:

.\excelize_bold.go:17:30: cannot use `{"font":{"bold":true,"italic":true,"family":"Berlin Sans FB Demi","size":36,"color":"#777777"}}` (untyped string constant "{\"font\":{\"bold\":true,\"italic\":true,\"family\":\"Berlin Sans FB...) as *excelize.Style value in argument to file.NewStyle

**Comment by xuri** [comment]
Hi @spyhunter925, please upgrade to the lasted version of this library, and reference the example 6 in the [documentation website](https://xuri.me/excelize/en/cell.html#SetCellStyle):

```go
f.SetCellValue("Sheet1", "D7", "Excel")
style, err := f.NewStyle(&excelize.Style{
    Font: &excelize.Font{
        Bold:   true,
        Italic: true,
        Family: "Times New Roman",
        Size:   36,
        Color:  "777777",
    },
})
if err != nil {
    fmt.Println(err)
}
err = f.SetCellStyle("Sheet1", "D7", "D7", style)
```

**Comment by spyhunter925** [comment]
ok, sorry for creating the duplicate. I noticed after I commented that this issue was closed and I thought you wouldn't be able to see it.

**Comment by spyhunter925** [comment]
Just tested and confirmed. It's working. Thanks :)
