### ISSUE TITLE
Newsheet is empty SetCellValue?

### ISSUE THREAD

**Issue by dohq** [Luxurioust/excelize#47]
```
$ go version
go version go1.8.1 windows/amd64
```

Code:
```go
package main

import (
	"fmt"
	"os"

	"github.com/Luxurioust/excelize"
)

func main() {
	xlsx := excelize.CreateFile()
	// Create a new sheet.
	xlsx.NewSheet(2, "List")
	// xlsx.DeleteSheet("Sheet1")
	// Set value of a cell.
	xlsx.SetCellValue("List", "A1", 100)
	xlsx.SetCellValue("List", "B1", 30)
	xlsx.SetCellFormula("List", "C1", "=A1+A2")
	// Set active sheet of the workbook.
	xlsx.SetActiveSheet(2)
	// Save xlsx file by the given path.
	err := xlsx.WriteTo("./dummy.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```
I changing "Create XLSX file Example"
But Cell is Empty...

[dummy.xlsx](https://github.com/Luxurioust/excelize/files/969663/dummy.xlsx)

I Tested MS Office2007

**Comment by Luxurioust** [comment]
@dohq Function `SetCellValue()` doesn't support get rows by sheet name currently, it need to name "Sheet" + index. Relate issue #25 and #43

**Comment by dlintw** [comment]
Does that mean we should use 'S'heet+index in this API. // uppercase
But, we should 's'heet+index in GetRows() API? // lowercase

**Comment by Luxurioust** [comment]
@dlintw Using both "Sheet" + index and "sheet" + index are working.

**Comment by dohq** [comment]
@Luxurioust Thankyou for replay

I will try

**Comment by pinpang** [comment]
I test this problem too.
I find the sheet name MUST in "Sheetn" and the "n" MUST equals xlsx.NewSheet(n, "Sheetn").

2017-05-05 

LiaoBin 



发件人：dohq <notifications@github.com>
发送时间：2017-05-02 15:12
主题：[Luxurioust/excelize] Newsheet Disable SetCellValue? (#47)
收件人："Luxurioust/excelize"<excelize@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

$ go version
go version go1.8.1 windows/amd64

Code:
package main

import (
	"fmt"
	"os"

	"github.com/Luxurioust/excelize"
)

func main() {
	xlsx := excelize.CreateFile()
	// Create a new sheet.
	xlsx.NewSheet(2, "List")
	// xlsx.DeleteSheet("Sheet1")
	// Set value of a cell.
	xlsx.SetCellValue("List", "A1", 100)
	xlsx.SetCellValue("List", "B1", 30)
	xlsx.SetCellFormula("List", "C1", "=A1+A2")
	// Set active sheet of the workbook.
	xlsx.SetActiveSheet(2)
	// Save xlsx file by the given path.
	err := xlsx.WriteTo("./dummy.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
I changing "Create XLSX file Example"
But Cell is Empty...
dummy.xlsx
I Tested MS Office2007

**Comment by dohq** [comment]
@Luxurioust 
I tested createsheet after GetSeheetIndex
I have tested the program and confirmed that it works as designed.
Thank you!
