### ISSUE TITLE
Can't display data cell in correct way

### ISSUE THREAD

**Issue by dlintw** [Luxurioust/excelize#48]
For example,
tealeg/xlsx display the same cell as: &{<nil> 42740  0xc420424640 mm-dd-yy false false 0 0 2}
throught it's .String() will convert to '01-05-17'

Luxurioust/excelize: just display as 42740 (already converted to string)

**Comment by Luxurioust** [comment]
@dlintw Thanks for your issue. I have fixed this issue.
