### ISSUE TITLE
Read file row by row

### ISSUE THREAD

**Issue by gshilin** [Luxurioust/excelize#5]
Is there any way to read excel by rows, like in tealeg's case:

``` go
for _, row = range sheet.Rows
```

in case I don't know how many rows are there?

**Comment by xpbliss** [comment]
the question is the same as the above.

**Comment by NaySoftware** [comment]
I've submitted a pull request solving this issue.

**Comment by Luxurioust** [comment]
@NaySoftware Nice, thanks for your PR.
