### ISSUE TITLE
Inserted Picture Shows Error

### ISSUE THREAD

**Issue by coolboy0002001** [Luxurioust/excelize#52]
When read a xlsx file with  complex border , Inserted picture shows error.
![1494499107](https://cloud.githubusercontent.com/assets/8806281/25945526/cac39746-3679-11e7-9c02-cc649cd6856d.png)
![1494499121](https://cloud.githubusercontent.com/assets/8806281/25945534/d2b29f7e-3679-11e7-9f51-355f3cc44730.png)
[Workbook.xlsx](https://github.com/Luxurioust/excelize/files/992721/Workbook.xlsx)

```
func main() {
	xlsx, _ := excelize.OpenFile("./Workbook.xlsx")

	err := xlsx.AddPicture("Sheet1", "A2", "./1.jpg", `{"x_offset": 15, "y_offset": 10, "print_obj": true, "lock_aspect_ratio": false, "locked": false}`)
	if err != nil {
		fmt.Println(err)
	}
	err = xlsx.WriteTo("./Workbook1.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

**Comment by Luxurioust** [comment]
@coolboy0002001 I tested it works well under commit [66349f8](https://github.com/Luxurioust/excelize/tree/66349f8ec039351770536b83b87c455543c0cf8a) and go1.8.1 darwin/amd64. Try upgrade library to the last version by `go get -u github.com/Luxurioust/excelize` and attach broken file `Workbook1.xlsx` if you can.

**Comment by coolboy0002001** [comment]
It works!  I tested it in an old go version!

**Comment by coolboy0002001** [comment]
It works! Error because I tested it in an old go version!
