### ISSUE TITLE
rows.go : getTotalRowsCols: ignoring error returned by xml.Token()

### ISSUE THREAD

**Issue by weizman** [Luxurioust/excelize#53]
when calling `.Token()` function of type `*xml.Decoder`, error returned is ignored when it should be handled.
line: `token, err := decoder.Token()` inside function `getTotalRowsCols()`

**Comment by Luxurioust** [comment]
The `token` is `nil` when `error != nil`, so it can be ignore and function `GetRows` won't throw an exception.
