### ISSUE TITLE
Adding picture to a sheet with existing pictures

### ISSUE THREAD

**Issue by samix73** [Luxurioust/excelize#58]
When I open an existing xlsx file and try to add a picture to a sheet which already has some pictures in it,  existing pictures will be corrupted or removed and the picture I'm trying to add is not added to the sheet.

My code:

``` go
func main() {
	xlsx, err := excelize.OpenFile("./tmp.xlsx")
	if err != nil {
		log.Println(err)
	 }

	if err = xlsx.AddPicture("Sheet1", "E5", "./test.jpg", `{"x_scale": 1, "y_scale": 1}`); err != nil {
		log.Println(err)
	}

	err = xlsx.WriteTo("./Workbook.xlsx")
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}
}
```

Base xlsx file:
[tmp.xlsx](https://github.com/Luxurioust/excelize/files/1049467/tmp.xlsx)

After adding the picture:
[Workbook.xlsx](https://github.com/Luxurioust/excelize/files/1049468/Workbook.xlsx)

**Comment by Luxurioust** [comment]
Thanks for your issue, I have fixed it by adding relationships in drawing content type shall.
