### ISSUE TITLE
Slow SetCellStyle for large amount of cells

### ISSUE THREAD

**Issue by pjmuller** [Luxurioust/excelize#60]
Hi Luxurioust,

when I want to apply a style to a larger (but not huge) amount of cells it takes more than a minute (see code below)

`err = xlsx.SetCellStyle("Sheet1", "A1", "A6500", `{"alignment":{"wrap_text":true}}`)`

Is there a way to improve this? FYI: I want to apply this style to the whole spreadsheet, so if there is a more performant way to do this, shoot! (Sidenote 2: writing the file is also A LOT slower when these cell styles have been applied)

Also, I'm calling ` xlsx.SetCellValue("Sheet1", laxis, value)` 6500 times. This is done quite quickly but could it not be faster if we pass a `[]interface{}` or `[][]interface{}` to something like `SetCellValueArea()` ?

Greetings,
PJ

**Comment by Luxurioust** [comment]
Thanks for your issue. I have fix it.

**Comment by pjmuller** [comment]
This is indeed fixed. Thanks!

My second question is still open, is there no more efficient way to pass a an array of 2D array of data instead of calling `xlsx.SetCellValue("Sheet1", laxis, value)` a very large number of times?

**Comment by plandem** [comment]
Well, for me it's still quite slow :( I have 3k rows with 14 cols and each row has at least 1 cell with style ("red background") to mark bad cell. Without styles it takes about 30sec to generate, but with styles 9 min!!! Is there any way to optimize it?

**Comment by xuri** [comment]
If the number of cells is large and all styles of the cell are same, we can set style with range in a batch instead of set the cell style one by one. In addition, how about use conditional formatting to mark a cell with bad value?
