### ISSUE TITLE
how to know the sheet or cell is hiden?

### ISSUE THREAD

**Issue by taihangg** [Luxurioust/excelize#61]
how to know the sheet or cell is hiden?

**Comment by Luxurioust** [comment]
Thanks for you issue, I have added new functions: `GetSheetVisible()` and `GetRowVisible()`, you can get visible state of sheet or row by these APIs.

Note that API changed:

Function `HideSheet()` and `UnhideSheet()` has been deprecated with `SetSheetVisible()` instead, function `HideRow()` and `UnhideRow()` has been deprecated with `SetRowVisible()` instead.

**Comment by taihangg** [comment]
@Luxurioust thank you. and is there a function with column?

**Comment by Luxurioust** [comment]
New functions `GetColVisible()` and `SetColVisible()` has been added.

**Comment by taihangg** [comment]
thank you
