### ISSUE TITLE
formattedValue function take too much time

### ISSUE THREAD

**Issue by shuimu98** [Luxurioust/excelize#64]
![image](https://user-images.githubusercontent.com/3291453/27527997-e9bb7a94-5a80-11e7-91b2-5ce9f6dd2e55.png)

**Comment by Luxurioust** [comment]
@shuimu98 Thanks for your issue, I have do some optimization to improve performance by avoid repeating deserialization style XML file.

**Comment by shuimu98** [comment]
thx，我再试一下

**Comment by shuimu98** [comment]
已经OK，读取速度和之前的版本一样了，3Q
