### ISSUE TITLE
toAlphaString() is very helpful.  Can it be made accessible from the excelize object?

### ISSUE THREAD

**Issue by gitdlam** [Luxurioust/excelize#66]
Hi thanks again for the great work.  I've been copying out the function **toAlphaString()** to use for myself. It would be neater to see it available direct from **excelize**, something like  **excelize.ToAphaString()**.   Yes?

**Comment by Luxurioust** [comment]
Function `ToAlphaString()` has been exported, please upgrade library to the last version by `go get -u github.com/Luxurioust/excelize`.

**Comment by gitdlam** [comment]
Thanks so much!! :)
