### ISSUE TITLE
Use function "GetRows" rather than function "GetCellValue" with looping construct to get better reading efficiency.

### ISSUE THREAD

**Issue by zzc-tongji** [Luxurioust/excelize#70]
Reading a .xlsx file with a sheet of 780 rows and 5 columns:

- Using function "GetRows": less that 1 second.
- Using function "GetCellValue" with looping construct: about 60 seconds.

Environment:

- golang 1.8 darwin/amd64
- Macbook Air (1.3 GHz CPU & 8GB RAM)

**Comment by Luxurioust** [comment]
Thanks for your issue, I have do some optimization to improve performance by avoid repeating deserialization style XML file.

**Comment by zzc-tongji** [comment]
Thanks.

PS: it is quite strange to communicate with another Chinese by using English. :-D
